"$schema" = "./node_modules/wrangler/config-schema.json"
name = "e-quiz"
main = "./worker/index.ts"
compatibility_date = "2026-07-03"
compatibility_flags = ["nodejs_compat_v2"]
workers_dev = false
dev.port = 3000

[vars]
AUTH0_AUDIENCE = "https://mikuroxina.jp.auth0.com/api/v2/"
AUTH0_DOMAIN = "mikuroxina.jp.auth0.com"
AUTH0_CLIENT_ID = "7diBR40dXPZwOH65zchO9514YFMySJxN"

[[d1_databases]]
binding = "e_quiz_db"
database_name = "e-quiz-db"
database_id = "dbf03e26-6f61-4c99-9174-836da531c23b"
migrations_dir = "drizzle/migrations"

[assets]
run_worker_first = ["/api/*"]
not_found_handling = "single-page-application"

[env.production.vars]
NODE_ENV = "production"
AUTH0_AUDIENCE = "https://mikuroxina.jp.auth0.com/api/v2/"
AUTH0_DOMAIN = "mikuroxina.jp.auth0.com"
AUTH0_CLIENT_ID = "7diBR40dXPZwOH65zchO9514YFMySJxN"

[[env.production.d1_databases]]
binding = "e_quiz_db"
database_name = "e_quiz_db_demo"
database_id = "36ba954e-a306-4cee-b341-dfe86dd506d8"
